[build]
  publish = "public/"
  command = "hugo --gc --minify --enableGitInfo"

[build.processing]
  skip_processing = true

[context.production.environment]
  HUGO_VERSION = "0.79.0"
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"

[[redirects]]
  from = "/ru/*"
  to = "/ru/404/"
  status = 404
[[redirects]]
  from = "/en/*"
  to = "/en/404/"
  status = 404
[[redirects]]
  from = "/*"
  to = "/en/404/"
  status = 404

[[redirects]]
  from = "/"
  to = "/en"
  status = 302
  force = true
  
[[headers]]
  for = "/*"
  [headers.values]
    Strict-Transport-Security = "max-age=63072000; includeSubdomains; preload"
    X-Frame-Options = "DENY"
    x-xss-protection = "1; mode=block"  
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "origin-when-cross-origin"
    cache-control = "max-age=2592000"
    Feature-Policy = "microphone 'none'; geolocation 'none'"