[build]
  publish = "public/"
  command = "hugo --gc --enableGitInfo"

[build.processing]
  skip_processing = true

[context.production.environment]
  HUGO_VERSION = "0.79.0"
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"

[[redirects]]
  from = "/"
  to = "/en/"
  status = 302
  force = true
  conditions = {Language = ["en"]}
[[redirects]]
  from = "/"
  to = "/ru/"
  status = 302
  force = true

[[redirects]]
  from = "/ru/*"
  to = "/ru/404/"
  status = 404
[[redirects]]
  from = "/en/*"
  to = "/en/404/"
  status = 404
[[redirects]]
  from = "/*"
  to = "/en/404/"
  status = 404

[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "max-age=1592001"
[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "max-age=1592002"
[[headers]]
  for = "*.woff2"
  [headers.values]
    Cache-Control = "max-age=1592003"



