[build]
  publish = "public/"
  command = "hugo --gc --enableGitInfo"

[build.processing]
  skip_processing = true

[context.production.environment]
  HUGO_VERSION = "0.79.0"
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"

[[redirects]]
  from = "/"
  to = "/en/"
  status = 302
  force = true
  conditions = {Language = ["en"]}
[[redirects]]
  from = "/"
  to = "/ru/"
  status = 302
  force = true

[[redirects]]
  from = "/ru/*"
  to = "/ru/404/"
  status = 404
[[redirects]]
  from = "/en/*"
  to = "/en/404/"
  status = 404
[[redirects]]
  from = "/*"
  to = "/en/404/"
  status = 404
  

# 86400 = 1 day
# 2678400 = 31 days
# 31536000 = 365 days

# Please cache this content, and then do not trust your cache
[[headers]]
  for = "/*"
  [headers.values]
    Strict-Transport-Security = "max-age=63072000; includeSubdomains; preload"
    X-Frame-Options = "DENY"
    X-XSS-protection = "1; mode=block"  
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "origin-when-cross-origin"
    Cache-Control = "max-age=0, must-revalidate, public"
[[headers]]
  for = "*.jpg"
  [headers.values]
    Cache-Control = "max-age=0, must-revalidate, public"

# 1 day
[[headers]]
  for = "*.png"
  [headers.values]
    Cache-Control = "max-age=86400, public, immutable"
[[headers]]
  for = "*.svg"
  [headers.values]
    Cache-Control = "max-age=86400, public, immutable"

# 31 days
[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "max-age=2678400, public, immutable"
[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "max-age=2678400, public, immutable"
[[headers]]
  for = "*.png"
  [headers.values]
    Cache-Control = "max-age=2678400, public, immutable"
[[headers]]
  for = "*.svg"
  [headers.values]
    Cache-Control = "max-age=2678400, public, immutable"
[[headers]]
  for = "*.ico"
  [headers.values]
    Cache-Control = "max-age=2678400, public, immutable"
[[headers]]
  for = "*.woff2"
  [headers.values]
    Cache-Control = "max-age=2678400, public, immutable"
